#! /bin/sh

# Path to GDB macros file.  Customize for your site.
GDBMACROS="/home/bhavidhingra/google-drive-iiith/Semester_#1/CSE531_OS_PG/Assignments/3/PintOS-Threads/pintos/src/misc/gdb-macros"

# Choose correct GDB.
if command -v i386-elf-gdb >/dev/null 2>&1; then
	GDB=i386-elf-gdb
else
	GDB=gdb
fi

# Run GDB.
if test -f "$GDBMACROS"; then
	exec $GDB -x "$GDBMACROS" "$@"
else
	echo "*** $GDBMACROS does not exist ***"
	echo "*** Pintos GDB macros will not be available ***"
	exec $GDB "$@"
fi
